# Generated by Django 5.2.4 on 2025-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custumer_phone',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
