# Generated by Django 5.2.4 on 2025-07-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_custumer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='custumer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='custumer_phone',
            field=models.CharField(max_length=10),
        ),
    ]
