# Generated by Django 5.2.4 on 2025-07-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_custumer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('service', 'date', 'time')},
        ),
    ]
