# Generated by Django 5.2.4 on 2025-07-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_options_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
