# Generated by Django 5.2.4 on 2025-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='active', max_length=20),
        ),
    ]
